services:
  - type: web
    name: itsutra-resume-tweaker
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    branch: master
    commit: cb275ef5acc4a790a1b64f467be7d2e7a93c1437
    healthCheckPath: /health
    healthCheckTimeout: 120
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: resume-tweaker-db
          property: connectionString
      - key: TRANSFORMERS_CACHE
        value: /tmp/transformers_cache
      - key: TORCH_HOME
        value: /tmp/torch_cache
      - key: CUDA_VISIBLE_DEVICES
        value: ""
      - key: FORCE_CPU
        value: "1"
      - key: PORT
        value: "10000"

databases:
  - name: resume-tweaker-db
    databaseName: resumetweaker
    user: resumetweaker
    plan: free

# Optional: Add HTTPS redirect
routes:
  - type: redirect
    source: /
    destination: https://itsutra-resume-tweaker.onrender.com
    permanent: true 